name: "Review Labeler"
description: "Adds labels based on review approvals or requested changes"
author: "eventology"
inputs:
  token:
    description: "github token"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
