version: 1
events:
  - users: [dev1, dev2, dev3]
    prApprove:
      addLabel: [code review pass]
      removeLabel: [pr ready for code review, ready for code review]
    prDeny:
      addLabel: [needs changes]
      removeLabel: [pr ready for code review, ready for code review]

  - users: [qa1, qa2, qa3]
    prApprove:
      addLabel: [qa pass]
      removeLabel: [pr ready for qa, ready for qa]
    prDeny:
      addLabel: [qa fail]
      removeLabel: [pr ready for qa, ready for qa]
