version: 1
groups:
  - users: [user1, user2]
    approval_labels: [code review pass]
    denial_labels: [needs changes]
    removed_labels: [pr ready for code review, ready for code review]
  - users: [user3, user4]
    approval_labels: [qa pass]
    denial_labels: [qa fail]
    removed_labels: [pr ready for qa, ready for qa]
