version: 1
events:
  - users: [dev1, dev2, dev3]
    pr_approve:
      add_label: code review pass
      remove_label: [pr ready for code review, ready for code review]
    pr_deny:
      add_label: needs changes
      remove_label: [pr ready for code review, ready for code review]

  - users: [qa1, qa2, qa3]
    pr_approve:
      add_label: qa pass
      remove_label: [pr ready for qa, ready for qa]
    pr_deny:
      add_label: qa fail
      remove_label: [pr ready for qa, ready for qa]
